#!/usr/bin/env sh

swayidle -w timeout 100 'wlock' &
wayland-pipewire-idle-inhibit &
kanshi &
fnott &
dbus-update-activation-environment \
	--systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

/home/yiyu/dotfiles/.config/river/orilla-config.rs &
sleep 1
yambar &
