#!/usr/bin/env sh

# long-running daemons; river SIGTERMs this process group on exit
wayland-pipewire-idle-inhibit &
kanshi &
fnott &
yambar &
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

export REKA=1
export RUST_LOG=reka=debug
emacs
