# The default theme for alacritty is OK, but there are two issues:
# 1. Green and bright green look like vomit.
# 2. The background color is not black.

[colors.bright]
green = "0x00FF00"

[colors.normal]
green = "0x008000"

[colors.primary]
background = "0x000000"
