# modus-vivendi
[colors.bright]
green = "#44df44"
black = "#6b6b6b"
red = "#ff5f5f"
yellow = "#efef00"
blue = "#338fff"
magenta = "#ff66ff"
cyan = "#00eff0"
white = "#989898"

[colors.normal]
green = "#44bc44"
black = "#000000"
red = "#ff5f59"
yellow = "#d0bc00"
blue = "#2fafff"
magenta = "#feacd0"
cyan = "#00d3d0"
white = "#ffffff"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
